FROM python:3.11

WORKDIR /app

RUN pip install catboost explainerdashboard scikit-learn pandas joblib flask numpy

COPY . .

RUN python generate_dashboard.py

EXPOSE 9050

CMD ["python", "run_dashboard.py"]
